name: Node Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
#    if: ${{ contains(github.event.pull_request.title, 'release:') }}
    name: bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install cargo-edit
        run: |
          cargo install cargo-edit
      - id: set-version
        continue-on-error: false
        run: |
          echo ${{ cargo set-version --bump patch --package pendulum-node }} >> "$GITHUB_OUTPUT"
      - name: Verify Changed files
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v20
        with:
          files: |
            node/*
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          base: "main"
          labels: "merge when passing"
          title: "release: upgrade node"
          branch: "release/upgrade-to-${{ steps.set-version.output }}"
          body: "Upgrade Node ${{ steps.set-version.output }}"
          token: ${{ secrets.PAT_TOKEN }}

