name: check-diff

# Run on all pull_request related events
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read # this is necessary for the Action to be able to read the contents of the repo

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to checkout all branches for this Action to work
     # git checkout
      - name: check for file differences
        run: git diff --compact-summary --word-diff-regex=spec_version -q runtime/amplitude/src/lib.rs >> diff.txt
      - name: print out the differences
        run: cat diff.txt


