name: "Release"

on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#  push:
  pull_request:
    branches:
      - main

jobs:
  check-for-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if PR titles says it's for release
        if: ${{ contains(github.event.pull_request.title, 'release') }}
        run: |
          echo "FOR_RELEASE=1" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Check if for Amplitude runtime
        if: ${{ env.FOR_RELEASE == 1 && contains(env.PR_TITLE, 'Amplitude') }}
        run: |
          echo "RELEASE_RUNTIME=amplitude" >> $GITHUB_ENV
      - name: Check if for Pendulum runtime
        if: ${{ env.FOR_RELEASE == 1 && contains(env.PR_TITLE, 'Pendulum') }}
        run: |
          echo "RELEASE_RUNTIME=pendulum" >> $GITHUB_ENV
      - name: Print the runtime
        run: |
            echo This is for ${{ env.RELEASE_RUNTIME }} runtime


