name: "Release"

on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#  push:
  pull_request:
    branches:
      - main

jobs:
  check-for-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if PR titles says it's for release
        if: ${{ contains(github.event.pull_request.title, 'release') }}
        run: |
          echo "FOR_RELEASE=true" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Check if for Amplitude runtime
        if: ${{ $FOR_RELEASE  == 1 && contains($PR_TITLE, 'amplitude) }}
        run: |
          echo "RELEASE_RUNTIME=amplitude" >> $GITHUB_ENV
      - name: Check if for Pendulum runtime
        if: ${{ $FOR_RELEASE == 1 && contains($PR_TITLE, 'pendulum') }}
        env:
          RELEASE_RUNTIME: Pendulum
      - name: Print the runtime
        env:
            echo This is for $RELEASE_RUNTIME runtime


